---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
      box_url: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[socialmind::default]
    encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"
    attributes:
