name             'socialmind'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures base'
long_description 'Installs/Configures base'
version          '0.1.0'

depends 'git'
depends 'build-essential'
depends 'apt'
depends 'nginx'
depends 'mongodb'
